### ISSUE TITLE
JSON schema for I-V curve files

### ISSUE THREAD

**Issue by markcampanelli** [cwhanse/ivcurves#2]
@cwhanse I decided to use "Issues" to provide feedback on this effort. You might consider opening up the "Discussions" section for this repo, which might be more appropriate for these items, which are really up for discussion :). Thanks to you and your team for taking on this project.

My first idea is to provide a JSON schema for the I-V curve files. The one that I am familiar with is https://json-schema.org/learn/getting-started-step-by-step, which has at least one Python implementation: https://python-jsonschema.readthedocs.io/en/stable/. Among other things, this should allow users to check if their files are formatted correctly.

**Comment by markcampanelli** [comment]
One related issue here: The units of the Voltage and Current could be made more explicit in the JSON files. When working with 2" reference cells, mA is not uncommon for the current (sometimes also mV for voltage), so it would be convenient (but by no means necessary) to allow other units. Either way, it seems like documenting the units makes the JSON files more self contained and foolproof.

**Comment by markcampanelli** [comment]
Seems like including the series cells per string and parallel strings per device would make the I-V curve files more self-contained.

If these files are eventually used for shading studies, then more circuit-topology info could be useful, such as bypass diodes, but that gets complicated and probably could be left for v2.

**Comment by markcampanelli** [comment]
Metadata around the irradiance and temperature seem warranted. For example, back of module average temperature vs. an embedded temperature probe directly touching the backside of a reference cell. Also, what is the spectrum of the irradiance?

**Comment by cwhanse** [comment]
Thanks, Mark, great suggestions. I've opened discussions. I agree - we should publish a json schema file rather than assuming the `caseX.json` instance files provide a sufficient description. I would like to keep the schema as light as reasonable, though. And we intend to provide python code to aid in writing IV curve instance files (using the schema) and reading instance documents.

Fore measured IV curves, we should definitely extend the schema to include metadata about the measurements, including irradiance and temperature. We've focused on getting the synthetic curves published and standing up the equation fitting evaluator. Published measured IV curves will take longer - we've been looking at our own measurements and finding issues with the data and/or the measurement process.

**Comment by markcampanelli** [comment]
One more suggestion: The I-V curves are naturally ordered/indexed as members of the "IV Curves" JSON array. Thus, I would rename the  "Index" key to "Label" and allow users to provide custom label strings for each curve.

This could satisfy, for example, a typical use case where each curve is read in from a separate file, and the user could naturally assign the filename as the label of each curve. Such labels could likewise refer to the nominal temperature and irradiance combination in the IEC 61853-1 matrix.
